language: c++
sudo: false
git:
  depth: 1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=gcc-5
        - COMPILERXX=g++-5
        - VARIANT=Release
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=gcc-6
        - COMPILERXX=g++-6
        - VARIANT=Release
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=gcc-7
        - COMPILERXX=g++-7
        - VARIANT=Coverage
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=gcc-7
        - COMPILERXX=g++-7
        - VARIANT=ASan
        # TEMP
        - ASAN_OPTIONS=detect_leaks=0
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=gcc-7
        - COMPILERXX=g++-7
        - VARIANT=UBSan
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'g++-7']
      env:
        - COMPILER=clang-5.0
        - COMPILERXX=clang++-5.0
        - VARIANT=Release

cache:
  apt: true
  directories:
    - ".travis/cmake"
    - ".travis/boost"
    - ".travis/lcov"

before_install:
  - export CC="$COMPILER" && export CXX="$COMPILERXX"
  - pushd . && source "./scripts/update-cmake.sh" && popd
  - pushd . && source "./scripts/update-boost.sh" && popd
  - pushd . && source "./scripts/update-lcov.sh"  && popd
  - pip install --user codecov

script:
  - ./scripts/build-and-test.sh

notifications:
  email: false
