version: "1.0.{build}"

os: Visual Studio 2022

environment:
  global:
    BOOST_INCLUDEDIR: "C:/Libraries/boost_1_77_0"
    CMAKE_GENERATOR_NAME: "Visual Studio 17 2022"
  matrix:
    - CMAKE_ARCHITECTURE_NAME: "Win32"
      BOOST_LIBRARYDIR: "C:/Libraries/boost_1_77_0/lib32-msvc-14.3"
    - CMAKE_ARCHITECTURE_NAME: "x64"
      BOOST_LIBRARYDIR: "C:/Libraries/boost_1_77_0/lib64-msvc-14.3"
cache:
  - C:\Users\appveyor\AppData\Local\vcpkg\archives

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cd C:\Tools\vcpkg
  - git fetch origin && git reset --hard 2022.08.15
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - cmd: cmake -B build -G "%CMAKE_GENERATOR_NAME%" -A "%CMAKE_ARCHITECTURE_NAME%" --toolchain C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build_script:
  - cmd: cmake --build build --config Release -- /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - cmd: build\\tests\\Release\\kl-tests -r junit -o results.xml

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = 'results.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))
